#!/usr/bin/env bash

./build
./build-linux
(
cd ../provisio-binaries
version="$(cat VERSION | tr -d '\n')"
version=$((version+1))
echo ${version} > VERSION
gacp
git tag 0.0.${version}
git push --tags
)
