FROM ubuntu:bionic

ARG VERSION

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install git curl unzip -y && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

COPY tools /root/.provisio/tools
COPY target/provisio-tools-${VERSION}-runner /root/.provisio/provisio
COPY provisio.yaml /root/.provisio/profiles/tools/profile.yaml
