#!/usr/bin/env bash

source maven.bash
version=$(mavenProjectVersion "pom.xml")
if echo "${version}" | grep SNAPSHOT ; then
  # 0.0.X-SNAPSHOT --> 0.0.X
  version=$(echo ${version} | sed -e 's/-SNAPSHOT//')
  ./mvnw versions:set -DnewVersion="${version}"
  rm -f pom.xml.versionsBackup
  git add pom.xml; git commit -m "Release ${version}"; git tag ${version}; git push && git push --tags
  # 0.0.X --> X
  version="$(echo ${version} | sed -e 's/0.0.//')"
  # X --> 0.0.X+1-SNAPSHOT
  version="0.0.$((version+1))-SNAPSHOT"
  ./mvnw versions:set -DnewVersion="${version}"
  rm -f pom.xml.versionsBackup
else
  echo "${version} is not a SNAPSHOT. Exiting."
  exit
fi
