#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"

function updateTools() {
  profile="${1}"
  OS=$(uname)
  ARCH=$(uname -m)
  PROVISIO_ROOT=~/.provisio
  PROVISIO_VERSION="$(curl -s -L https://api.github.com/repos/jvanzyl/provisio-tools/releases | grep tag_name | head -1 | sed -e 's/.*: "//' -e 's/".*$//')"
  PROVISIO_BINARY="provisio"
  PROVISIO_BINARY_FILE="provisio-${OS}-x86_64"
  PROVISIO_BINARY_URL="https://github.com/jvanzyl/provisio-tools/releases/download/${PROVISIO_VERSION}/${PROVISIO_BINARY_FILE}"

  if [ ! -f ${PROVISIO_ROOT}/${PROVISIO_BINARY} ]; then
    echo
    echo "Downloading ${PROVISIO_BINARY_URL} ..."
    echo
    mkdir -p ${PROVISIO_ROOT} > /dev/null 2>&1
    curl -L -o ${PROVISIO_ROOT}/${PROVISIO_BINARY} ${PROVISIO_BINARY_URL}
    chmod +x ${PROVISIO_ROOT}/${PROVISIO_BINARY}
  fi

  profileYaml=".provisio/profiles/sre/profile.yaml"
  profileYamlTemplate="${profileYaml}.mustache"
  sed -e "s/{{arch}}/${ARCH}/" ${profileYamlTemplate} > ${profileYaml}

  ${PROVISIO_ROOT}/${PROVISIO_BINARY} install ${profile}
  source ${PROVISIO_ROOT}/bin/profiles/profile/.init.bash
}

updateTools sre
