---
id: ck8s-cli
name: ck8s cli
defaultVersion: 0.1.17
layout: file
executable: ck8s
packaging: FILE
# https://github.com/concord-workflow/ck8s-cli/releases/download/0.1.10/ck8s-cli-0.1.10-executable.jar
urlTemplate: https://github.com/concord-workflow/ck8s-cli/releases/download/{version}/ck8s-cli-{version}-executable.jar
